#sudo virt-install --name AlmaLinux-server --ram=2048 --vcpus=2 --cpu host --hvm --
#disk path=/var/lib/libvirt/images/almalinuxservervml,size=20 --cdrom /var/lib/libvirt/boot/AlmaLinux-8.4-x86_64-DVD.iso --graphics vnc


#!/bin/bash
# VM Creation Script - Generated by Multi-Server Setup Tool
# Configuration Date: 11/07/2025
# VM1: ubuntu-24.04 for ubuntu.nepal.it.com
# VM2: almalinux-9.6 for almalinux.nepal.it.com

set -e

echo "=== Creating VMs ==="
echo "VM1: ubuntu-24.04 (4G RAM, 2 CPU, 50G Disk)"
echo "VM2: almalinux-9.6 (4G RAM, 2 CPU, 50G Disk)"

# Create storage directory
mkdir -p /var/lib/libvirt/images

# Download OS images (you'll need to adjust URLs based on your setup)
echo "Downloading OS images..."
cd /var/lib/libvirt/images

# VM1 Image
if [[ "ubuntu-24.04" == *"ubuntu"* ]]; then
    VM1_IMAGE="ubuntu-24.04-server-cloudimg-amd64.img"
    if [ ! -f "$VM1_IMAGE" ]; then
        echo "Downloading Ubuntu 24.04 LTS cloud image..."
        wget -O "$VM1_IMAGE" https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
    fi
elif [[ "ubuntu-24.04" == *"almalinux"* ]]; then
    VM1_IMAGE="AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
    if [ ! -f "$VM1_IMAGE" ]; then
        echo "Downloading AlmaLinux 9 cloud image..."
        wget -O "$VM1_IMAGE" https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
    fi
fi

# VM2 Image
if [[ "almalinux-9.6" == *"ubuntu"* ]]; then
    VM2_IMAGE="ubuntu-24.04-server-cloudimg-amd64.img"
    if [ ! -f "$VM2_IMAGE" ]; then
        echo "Downloading Ubuntu 24.04 LTS cloud image..."
        wget -O "$VM2_IMAGE" https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
    fi
elif [[ "almalinux-9.6" == *"almalinux"* ]]; then
    VM2_IMAGE="AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
    if [ ! -f "$VM2_IMAGE" ]; then
        echo "Downloading AlmaLinux 9 cloud image..."
        wget -O "$VM2_IMAGE" https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
    fi
fi

# Create VM1
echo "Creating VM1 for ubuntu.nepal.it.com..."
cp "$VM1_IMAGE" "vm1-ubuntu.nepal.it.com.qcow2"
qemu-img resize "vm1-ubuntu.nepal.it.com.qcow2" 50G

# Create cloud-init config for VM1
cat > vm1-cloud-init.yaml << EOF
#cloud-config
hostname: vm1-ubuntu.nepal.it.com
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
package_update: true
package_upgrade: true
packages:
  - nginx
  - curl
  - wget
  - htop
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo "Welcome to ubuntu.nepal.it.com" > /var/www/html/index.html
EOF

cloud-localds vm1-cloud-init.iso vm1-cloud-init.yaml

virt-install \
    --name "vm1-ubuntu.nepal.it.com" \
    --memory 4000 \
    --vcpus 2 \
    --disk path="/var/lib/libvirt/images/vm1-ubuntu.nepal.it.com.qcow2",format=qcow2,bus=virtio \
    --disk path="/var/lib/libvirt/images/vm1-cloud-init.iso",device=cdrom \
    --import \
    --os-variant detect \
    --network bridge=virbr0,model=virtio \
    --graphics none \
    --console pty,target_type=serial \
    --noautoconsole \
    --boot hd

# Create VM2
echo "Creating VM2 for almalinux.nepal.it.com..."
cp "$VM2_IMAGE" "vm2-almalinux.nepal.it.com.qcow2"
qemu-img resize "vm2-almalinux.nepal.it.com.qcow2" 50G

# Create cloud-init config for VM2
cat > vm2-cloud-init.yaml << EOF
#cloud-config
hostname: vm2-almalinux.nepal.it.com
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH key here
package_update: true
package_upgrade: true
packages:
  - nginx
  - curl
  - wget
  - htop
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo "Welcome to almalinux.nepal.it.com" > /var/www/html/index.html
EOF

cloud-localds vm2-cloud-init.iso vm2-cloud-init.yaml

virt-install \
    --name "vm2-almalinux.nepal.it.com" \
    --memory 4000 \
    --vcpus 2 \
    --disk path="/var/lib/libvirt/images/vm2-almalinux.nepal.it.com.qcow2",format=qcow2,bus=virtio \
    --disk path="/var/lib/libvirt/images/vm2-cloud-init.iso",device=cdrom \
    --import \
    --os-variant detect \
    --network bridge=virbr0,model=virtio \
    --graphics none \
    --console pty,target_type=serial \
    --noautoconsole \
    --boot hd

echo "VMs created successfully!"
echo "VM1 IP should be: 192.168.1.101"
echo "VM2 IP should be: 192.168.1.102"
echo "Use 'virsh console vm1-ubuntu.nepal.it.com' to access VM1"
echo "Use 'virsh console vm2-almalinux.nepal.it.com' to access VM2"
echo "Made by Rabins Sharma Lamichhane for HostingSewa.com"
