#!/bin/bash
# Host Setup Script - Generated by Multi-Server Setup Tool
# Configuration Date: 11/07/2025
# Host OS: almalinux-9.6

set -e

echo "=== Host Setup for almalinux-9.6 ==="
echo "Setting up KVM virtualization on almalinux-9.6..."

# Update system
echo "Updating system packages..."
dnf update -y

# Install KVM and virtualization tools
echo "Installing KVM and virtualization tools..."
dnf install -y qemu-kvm libvirt virt-install virt-viewer bridge-utils virt-manager libvirt-daemon-config-network libvirt-daemon-kvm

# Enable and start libvirt service
systemctl enable --now libvirtd
systemctl enable --now virtnetworkd

# Verify KVM support
if [ -f /proc/cpuinfo ]; then
    if grep -q "vmx\|svm" /proc/cpuinfo; then
        echo "✓ Hardware virtualization support detected"
    else
        echo "⚠ Warning: Hardware virtualization support not detected"
    fi
fi

# Configure libvirt for current user
usermod -aG libvirt $(whoami)
usermod -aG kvm $(whoami)

# Configure default network (ensure it's started)
virsh net-autostart default
virsh net-start default 2>/dev/null || true

# Install web server for reverse proxy
echo "Installing nginx web server..."
dnf install -y nginx

# Install SSL tools
echo "Installing SSL provider tools (letsencrypt)..."
dnf install -y certbot python3-certbot-nginx epel-release

# Configure firewall
echo "Configuring firewall..."
firewall-cmd --permanent --add-service=http --add-service=https --add-service=ssh
firewall-cmd --permanent --add-port=80/tcp --add-port=443/tcp --add-port=22/tcp
firewall-cmd --reload

echo "Host setup complete!"
echo "Next: Create VMs and configure networking"
echo "Made by Rabins Sharma Lamichhane for HostingSewa.com"
